version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data
volumes:
  pgvolume:
